import type {
  ShoppingBusiness,
  ShoppingCatalog,
  ShoppingCategory,
  ShoppingProduct,
} from "./types"

export type { ShoppingCatalog }

/** @deprecated Solo para demos locales; el catálogo vive en la API pública. */
export const MOCK_BUSINESS_SLUG = "la-parrilla-del-centro"

export const MOCK_BUSINESS: ShoppingBusiness = {
  id: "biz-demo-1",
  slug: MOCK_BUSINESS_SLUG,
  name: "La Parrilla del Centro",
  tagline: "Delivery · Retiro en local",
  currencyCode: "UYU",
}

export const MOCK_CATEGORIES: ShoppingCategory[] = [
  { id: "cat-starter", name: "Entradas", tag: "STARTER" },
  { id: "cat-main", name: "Principales", tag: "MAIN" },
  { id: "cat-side", name: "Guarniciones", tag: "SIDE" },
  { id: "cat-salad", name: "Ensaladas", tag: "SALAD" },
  { id: "cat-drink", name: "Bebidas", tag: "DRINK" },
  { id: "cat-dessert", name: "Postres", tag: "DESSERT" },
  { id: "cat-snack", name: "Snacks", tag: "SNACK" },
  { id: "cat-special", name: "Especiales", tag: "SPECIAL" },
]

const img = (seed: string) =>
  `https://picsum.photos/seed/${seed}/400/400`

export const MOCK_PRODUCTS: ShoppingProduct[] = [
  {
    id: "prod-1",
    name: "Empanadas de carne (x3)",
    description: "Masa casera, relleno jugoso y ají molido.",
    price: 320,
    currencyCode: "UYU",
    imageUrl: img("empanadas"),
    categoryId: "cat-starter",
    available: true,
  },
  {
    id: "prod-2",
    name: "Provoleta a la parrilla",
    description: "Con orégano, aceite de oliva y tomate cherry.",
    price: 450,
    currencyCode: "UYU",
    imageUrl: img("provoleta"),
    categoryId: "cat-starter",
    available: true,
  },
  {
    id: "prod-3",
    name: "Asado de tira",
    description: "500 g a punto. Ideal para compartir.",
    price: 980,
    currencyCode: "UYU",
    imageUrl: img("asado"),
    categoryId: "cat-main",
    available: true,
  },
  {
    id: "prod-4",
    name: "Vacío a la leña",
    description: "400 g, jugoso, con chimichurri.",
    price: 890,
    currencyCode: "UYU",
    imageUrl: img("vacio"),
    categoryId: "cat-main",
    available: true,
  },
  {
    id: "prod-5",
    name: "Milanesa napolitana",
    description: "Con jamón, queso y papas fritas.",
    price: 720,
    currencyCode: "UYU",
    imageUrl: img("milanesa"),
    categoryId: "cat-main",
    available: true,
  },
  {
    id: "prod-6",
    name: "Papas fritas",
    description: "Porción generosa, crocantes.",
    price: 280,
    currencyCode: "UYU",
    imageUrl: img("fries"),
    categoryId: "cat-side",
    available: true,
  },
  {
    id: "prod-7",
    name: "Puré de calabaza",
    description: "Con manteca y nuez moscada.",
    price: 250,
    currencyCode: "UYU",
    imageUrl: img("pure"),
    categoryId: "cat-side",
    available: true,
  },
  {
    id: "prod-8",
    name: "Ensalada mixta",
    description: "Lechuga, tomate, cebolla y zanahoria.",
    price: 310,
    currencyCode: "UYU",
    imageUrl: img("salad"),
    categoryId: "cat-salad",
    available: true,
  },
  {
    id: "prod-9",
    name: "Coca-Cola 1.5 L",
    description: null,
    price: 180,
    currencyCode: "UYU",
    imageUrl: img("cola"),
    categoryId: "cat-drink",
    available: true,
  },
  {
    id: "prod-10",
    name: "Agua mineral 500 ml",
    description: "Con o sin gas.",
    price: 90,
    currencyCode: "UYU",
    imageUrl: img("water"),
    categoryId: "cat-drink",
    available: true,
  },
  {
    id: "prod-11",
    name: "Flan casero",
    description: "Con dulce de leche y crema.",
    price: 260,
    currencyCode: "UYU",
    imageUrl: img("flan"),
    categoryId: "cat-dessert",
    available: true,
  },
  {
    id: "prod-12",
    name: "Churros (x4)",
    description: "Rellenos de dulce de leche.",
    price: 290,
    currencyCode: "UYU",
    imageUrl: img("churros"),
    categoryId: "cat-dessert",
    available: false,
  },
  {
    id: "prod-13",
    name: "Papas bravas",
    description: "Con salsa picante de la casa.",
    price: 340,
    currencyCode: "UYU",
    imageUrl: img("bravas"),
    categoryId: "cat-snack",
    available: true,
  },
  {
    id: "prod-14",
    name: "Combo parrillero",
    description: "Asado + vacío + guarnición + bebida.",
    price: 1890,
    currencyCode: "UYU",
    imageUrl: img("combo"),
    categoryId: "cat-special",
    available: true,
  },
]
